### ISSUE TITLE
repetition / prob prob prob... output on multiple calls in version 0.3.0

### ISSUE THREAD

**Issue by Sharrnah** [guillaumekln/faster-whisper#79]
I noticed an issue with the new version that i basically get every second call of transcribe() the repetition of the previous result Or just a bunch of "prob prob prob prob prob prob".

Not exactly sure what is causing this. but it only happens with v0.3.0 (and CTranslate 0.10.x since thats required with faster-whisper v0.3.0)

When i downgraded to faster-whisper 0.3.0 and CTranslate 0.9.0, the issue went away.

This could also be a result of me calling it in threads but i am not really sure yet.
The repetition might have been a side-effect of my audio queue, since after i moved the q.task_done() call above of starting the thread, it started outputting the "prob prob prob prob prob" texts quite often.

**Comment by Sharrnah** [comment]
Okay. i am confused now. i tried to reproduce it but i can't.

Is it possible that this only happens when i am running a GPU / CPU demanding Game at the same time?

But since it seems to work on 0.2.0 with no issues, i think i will downgrade for now.

**Comment by guillaumekln** [comment]
> repetition of the previous result

This reminds of issue #28 where the incorrect `initial_prompt` was passed to the model due to a bug in the multithreaded application.

Can you check for that? Otherwise it would be great if you can share a way to reproduce the issue.

**Comment by Sharrnah** [comment]
I removed the threaded calling and the issue still appeared. Even though now it was mostly just "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!".
Checked the audio that the AI receives and it sounded okay.
Downgraded to faster-whisper v0.2.0 and CTranslate2 on v3.8.0 and so far have not noticed that issue again.

I digged through my code and could not see anything that might relate to what you mentioned. But it seems to happen mostly when transcribing multiple things very quickly after each another without much pause between the calls.

will see if i can make a small example to reproduce if it won't happen again with v0.2.0. But since its not always happening, its not so easy to reproduce reliably.

**Comment by guillaumekln** [comment]
Are you using multiple model workers (`num_workers>1`)?

**Comment by guillaumekln** [comment]
I fixed a [bug](https://github.com/OpenNMT/CTranslate2/pull/1150) that could be related to your issue.

Can you update to `ctranslate2>=3.10.3` and try again?

**Comment by Sharrnah** [comment]
thanks. Still happened today with ctranslate2 v3.10.3 and faster-whisper master.

But definetly had two workers active.

will try further with only one worker next time.

**Comment by guillaumekln** [comment]
For reference, I used the code below to detect the issue when multiple GPU workers are used. It launches multiple threads and log the transcription when it does not match the reference.

With `ctranslate2==3.10.2` some transcriptions are sometimes completely invalid, but there is no such issues with `ctranslate2==3.10.3`.

```python
import threading

from faster_whisper import WhisperModel, decode_audio

def run(model, audio, expected):
    while True:
        segments, info = model.transcribe(audio, beam_size=1, without_timestamps=True)
        text = "".join(segment.text for segment in segments)
        if text != expected:
            print(threading.get_ident(), text)

num_workers = 2
num_threads = 2

model = WhisperModel("tiny", device="cuda", compute_type="float16", num_workers=num_workers)
audio = decode_audio("tests/data/jfk.flac")
expected = " And so my fellow Americans ask not what your country can do for you ask what you can do for your country."

threads = [threading.Thread(target=run, args=[model, audio, expected]) for _ in range(num_threads)]

for th in threads:
    th.start()
for th in threads:
    th.join()
```

Just to make sure, can you double check you have version 3.10.3 installed?

**Comment by Sharrnah** [comment]
sorry for the wrong claim that its still wrong. I tested it so far and could not notice the issue again.

so i guess its really fixed. :) Thank you.

**Comment by guillaumekln** [comment]
Ok, thank you! Please reopen if there is something else.
